# Jekyll config file

# Site settings
title_short: DataCleaner
title: The premier open source Data Quality solution | DataCleaner
description: >
  Open source software for data quality, data profiling, data warehousing, data wrangling,
  master data management, business intelligence and governance.
releases: [
  {"version": "5.5.0"},
  {"version": "5.4.2"},
  {"version": "5.4.1"},
  {"version": "5.4.0"},
  {"version": "5.3.0"},
  {"version": "5.2.2"},
  {"version": "5.2.1"},
  {"version": "5.2.0","sourceforge":true},
  {"version": "5.1.5","sourceforge":true},
  {"version": "5.1.4","sourceforge":true},
  {"version": "5.1.3","sourceforge":true},
  {"version": "5.1.2","sourceforge":true},
  {"version": "5.0.3","sourceforge":true},
  {"version": "5.0.2","sourceforge":true},
  {"version": "5.0","sourceforge":true},
  {"version": "4.5","sourceforge":true},
  {"version": "4.0.2","sourceforge":true},
  {"version": "4.0.1","sourceforge":true},
  {"version": "4.0","sourceforge":true}
]
docs:
- "5.4.0"
- "5.2"

google_analytics: "UA-110119916-1"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
